### ISSUE TITLE
team role readme for v1.1

### ISSUE THREAD

**Issue by ryoKkk** [askul/actions-github-organizer#25]
role settings(`maintainer` or `member`) for team membership.

**Comment by ryoKkk** [comment]
```yml
teams:
  - name: test_team
    org: test_org
    # member, maintainer, default is member
    role: member
  - name: test_team_sub
    org: test_org
    role: maintainer
```
